version: '3.8'
services:
  library:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
     - .:/home/app/library
     - /home/app/library/node_modules
